---
title: "gamezoneR_EDA"
author: "me"
date: "10/31/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```



```{r}
# Install via devtools package using the following:
devtools::install_github(repo = "JackLich10/gamezoneR")
```



```{r}
future::plan("multisession")
tictoc::tic()
progressr::with_progress({
  pbp <- gamezoneR::load_gamezone_pbp(gamezoneR:::available_seasons())
})
tictoc::toc()

length(unique(pbp$game_id))

pbp %>% dplyr::filter(!is.na(loc_x)) %>% nrow()
```



```{r}
ark_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Arkansas", season = "2021-22")
uk_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Kentucky", season = "2021-22")
ala_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Alabama", season = "2021-22")
lsu_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "LSU", season = "2021-22")
tamu_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Texas A&M", season = "2021-22")
mst_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Mississippi State", season = "2021-22")
miss_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Ole Miss", season = "2021-22")
sc_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "South Carolina", season = "2021-22")
uga_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Georgia", season = "2021-22")
uf_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Florida", season = "2021-22")
vand_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Vanderbilt", season = "2021-22")
aub_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Auburn", season = "2021-22")
mizz_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Missouri", season = "2021-22")
tenn_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Tennessee", season = "2021-22")
```

```{r}
wsu_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Wichita State", season = "2021-22")
asu_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Arizona State", season = "2021-22")
ri_schedule <- gamezoneR::gamezone_mbb_team_schedule(team = "Rhode Island", season = "2021-22")
```

```{r}
ark_pbp <- purrr::map_df(ark_schedule$game_id, 
                          gamezoneR::gamezone_mbb_pbp, sub_parse = F)
```


```{r}
ark_pbp %>%
  dplyr::filter(!is.na(poss_before)) %>%
  dplyr::mutate(poss_number = as.numeric(poss_number),
                shot_made_numeric = dplyr::case_when(
                  is.na(shot_outcome) ~ NA_real_,
                  shot_outcome == "made" ~ 1,
                  shot_outcome == "missed" ~ 0),
                shot_value = dplyr::case_when(
                  is.na(shot_outcome) ~ NA_real_,
                  free_throw == 1 ~ 1,
                  three_pt == 1 ~ 3,
                  T ~ 2),
                points = dplyr::case_when(
                  shot_made_numeric == 0 ~ 0,
                  shot_made_numeric == 1 & free_throw == 1 ~ 1,
                  shot_made_numeric == 1 & three_pt == 1 ~ 3,
                  shot_made_numeric == 1 & three_pt == 0 & free_throw == 0 ~ 2)) %>%
  dplyr::group_by(date, game_id, poss_before, poss_number) %>%
  dplyr::summarise(fgm = sum(shot_outcome == "made" & free_throw == F, na.rm = T),
                   fga = sum(!is.na(shot_outcome) & free_throw == F),
                   ftm = sum(shot_outcome == "made" & free_throw == T),
                   fta = sum(!is.na(shot_outcome) & free_throw == T),
                   points = sum(points, na.rm = T),
                   .groups = "drop") %>%
  dplyr::group_by(date, game_id, poss_before) %>%
  dplyr::summarise(poss = dplyr::n(),
                   across(fgm:points, sum),
                   .groups = "drop") %>%
  dplyr::mutate(ppp = points/poss,
                type = ifelse(poss_before == "Arkansas", "Offense", "Defense"),
                color = ifelse(poss_before == "Arkansas", "black", "#003366"),
                fill = ifelse(poss_before == "Arkansas", "#001A57", "white")) %>%
  ggplot(aes(date, ppp, fill = fill, color = color)) +
  geom_line() +
  geom_point(aes(size = poss),
             pch = 21, stroke = 0.9) +
  scale_color_identity() +
  scale_fill_identity() +
  scale_size_continuous(range = c(0.8, 3.5)) +
  labs(title = "Arkansas' offensive and defensive efficiency by game",
       subtitle = "2021-22 college basketball season",
       x = "Date",
       y = "Points per possession",
       size = "# of possessions",
       caption = "Chart: @jacobhaarala | Data: @gamezoneR") +
  theme()
```




```{r}
future::plan("multisession")
progressr::with_progress({
  pbp <- gamezoneR::load_gamezone_pbp(c("2017-18", "2018-19", "2019-20", "2020-21", "2021-22"))
})
```


```{r}
pbp_summarized <- pbp %>%
  dplyr::distinct() %>% 
  dplyr::filter(!is.na(poss_before)) %>%
  dplyr::mutate(poss_number = as.numeric(poss_number),
                shot_made_numeric = dplyr::case_when(
                  is.na(shot_outcome) ~ NA_real_,
                  shot_outcome == "made" ~ 1,
                  shot_outcome == "missed" ~ 0),
                shot_value = dplyr::case_when(
                  is.na(shot_outcome) ~ NA_real_,
                  free_throw == 1 ~ 1,
                  three_pt == 1 ~ 3,
                  T ~ 2),
                points = dplyr::case_when(
                  shot_made_numeric == 0 ~ 0,
                  shot_made_numeric == 1 & free_throw == 1 ~ 1,
                  shot_made_numeric == 1 & three_pt == 1 ~ 3,
                  shot_made_numeric == 1 & three_pt == 0 & free_throw == 0 ~ 2)) %>%
  dplyr::group_by(season, date, game_id, poss_before, poss_number) %>%
  dplyr::summarise(fgm = sum(shot_outcome == "made" & free_throw == F, na.rm = T),
                   fga = sum(!is.na(shot_outcome) & free_throw == F),
                   ftm = sum(shot_outcome == "made" & free_throw == T),
                   fta = sum(!is.na(shot_outcome) & free_throw == T),
                   points = sum(points, na.rm = T),
                   .groups = "drop") %>%
  dplyr::group_by(season, date, game_id, poss_before) %>%
  dplyr::summarise(poss = dplyr::n(),
                   across(fgm:points, sum),
                   .groups = "drop") %>%
  dplyr::mutate(ppp = points/poss)
```




```{r}
wsu_pbp <- purrr::map_df(wsu_schedule$game_id, 
                          gamezoneR::gamezone_mbb_pbp, sub_parse = F)
```



```{r}

# Let’s plot some shot charts. We will use the built in gamezoneR::base_court ggplot court.

wsu_shots <- wsu_pbp %>% 
  dplyr::filter(!is.na(loc_x),
                shooter == "Ricky Council IV")

gamezoneR::base_court +
  geom_point(data = wsu_shots,
             aes(loc_x, loc_y, color = shot_outcome),
             alpha = 0.8) +
  theme(axis.line = element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 30/.pt, margin = margin(0, 0, 5, 0)),
        plot.subtitle = element_text(face = "italic", hjust = 0.5, size = 24/.pt),
        plot.caption = element_text(face = "italic", hjust = 1, size = 20/.pt, margin = margin(0, 0, 0, 0)),
        legend.spacing.x = grid::unit(0, 'cm'),
        legend.title = element_text(size = 20/.pt, face = "bold"),
        legend.text = element_text(size = 16/.pt),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = 'bottom',
        legend.box.margin = margin(-35, 0, 0, 0),
        plot.margin = margin(5, 0, 5, 0)) +
  labs(title = "All of Ricky Council IV's shots at Wichita St",
       subtitle = "2021-22 college basketball season",
       color = "Outcome",
       caption = "Chart: @jacobhaarala | Data: @gamezoneR")
```




```{r}

ark_shots <- ark_pbp %>% 
  dplyr::filter(!is.na(loc_x),
                shooter == "Davonte Davis")

gamezoneR::base_court +
  geom_point(data = ark_shots,
             aes(loc_x, loc_y, color = shot_outcome),
             alpha = 0.8) +
  theme(axis.line = element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 30/.pt, margin = margin(0, 0, 5, 0)),
        plot.subtitle = element_text(face = "italic", hjust = 0.5, size = 24/.pt),
        plot.caption = element_text(face = "italic", hjust = 1, size = 20/.pt, margin = margin(0, 0, 0, 0)),
        legend.spacing.x = grid::unit(0, 'cm'),
        legend.title = element_text(size = 20/.pt, face = "bold"),
        legend.text = element_text(size = 16/.pt),
        legend.margin = margin(0, 0, 0, 0),
        legend.position = 'bottom',
        legend.box.margin = margin(-35, 0, 0, 0),
        plot.margin = margin(5, 0, 5, 0)) +
  labs(title = "All of Devo Davis' shots at Arkansas",
       subtitle = "2021-22 college basketball season",
       color = "Outcome",
       caption = "Chart: @jacobhaarala | Data: @gamezoneR")
```




```{r}
ark_shots <- ark_pbp %>%
  dplyr::filter(!is.na(loc_x))

gamezoneR::base_court +
  geom_point(data = ark_shots,
             aes(loc_x, loc_y, color = shot_outcome),alpha = 0.8) +
  theme(axis.line = element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 30/.pt, margin = margin(0, 0, 5, 0)),
        plot.subtitle = element_text(face = "italic", hjust = 0.5, size = 24/.pt),
        plot.caption = element_text(face = "italic", hjust = 1, size = 20/.pt, margin = margin(0, 0, 0, 0)),
        legend.spacing.x = grid::unit(0,'cm'),
        legend.title = element_text(size = 20/.pt, face = "bold"),
        legend.text = element_text(size = 16/.pt),
        legend.margin = margin(0, 0, 0, 0),
        legend.position ='bottom',
        legend.box.margin = margin(-35, 0, 0, 0),
        plot.margin = margin(5, 0, 5, 0)) +
  labs(title = "Arkansas Razorbacks Shot Chart",subtitle = "2021-22 college basketball season",
       color = "Outcome",caption = "Data: @gamezoneR")
```

```{r}
ala_pbp <- purrr::map_df(ala_schedule$game_id, 
                          gamezoneR::gamezone_mbb_pbp, sub_parse = F)
```




```{r}
ala_shots <- ala_pbp %>%
  dplyr::filter(!is.na(loc_x))

gamezoneR::base_court +
  geom_point(data = ala_shots,
             aes(loc_x, loc_y, color = shot_outcome),alpha = 0.8) +
  theme(axis.line = element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 30/.pt, margin = margin(0, 0, 5, 0)),
        plot.subtitle = element_text(face = "italic", hjust = 0.5, size = 24/.pt),
        plot.caption = element_text(face = "italic", hjust = 1, size = 20/.pt, margin = margin(0, 0, 0, 0)),
        legend.spacing.x = grid::unit(0,'cm'),
        legend.title = element_text(size = 20/.pt, face = "bold"),
        legend.text = element_text(size = 16/.pt),
        legend.margin = margin(0, 0, 0, 0),
        legend.position ='bottom',
        legend.box.margin = margin(-35, 0, 0, 0),
        plot.margin = margin(5, 0, 5, 0)) +
  labs(title = "Alabama Crimson Tide Shot Chart",subtitle = "2021-22 college basketball season",
       color = "Outcome",caption = "Data: @gamezoneR")
```


```{r}
aub_pbp <- purrr::map_df(aub_schedule$game_id, 
                          gamezoneR::gamezone_mbb_pbp, sub_parse = F)
```



```{r}
aub_shots <- aub_pbp %>%
  dplyr::filter(!is.na(loc_x))

gamezoneR::base_court +
  geom_point(data = aub_shots,
             aes(loc_x, loc_y, color = shot_outcome),alpha = 0.8) +
  theme(axis.line = element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5, size = 30/.pt, margin = margin(0, 0, 5, 0)),
        plot.subtitle = element_text(face = "italic", hjust = 0.5, size = 24/.pt),
        plot.caption = element_text(face = "italic", hjust = 1, size = 20/.pt, margin = margin(0, 0, 0, 0)),
        legend.spacing.x = grid::unit(0,'cm'),
        legend.title = element_text(size = 20/.pt, face = "bold"),
        legend.text = element_text(size = 16/.pt),
        legend.margin = margin(0, 0, 0, 0),
        legend.position ='bottom',
        legend.box.margin = margin(-35, 0, 0, 0),
        plot.margin = margin(5, 0, 5, 0)) +
  labs(title = "Auburn Tigers Shot Chart",subtitle = "2021-22 college basketball season",
       color = "Outcome",caption = "Data: @gamezoneR")
```





